import { StoryRegion } from './storyTypes';

export const STORY_REGIONS: StoryRegion[] = [
  {
    id: 'forest',
    name: 'Forêt Enchantée',
    icon: 'forest',
    description: 'Une forêt paisible envahie par les slimes...',
    unlockLevel: 1,
    bgColor: 'hsl(120, 30%, 15%)',
    stages: [
      { id: 'f1', name: 'Lisière', regionId: 'forest', stageNumber: 1, isBoss: false, width: 11, height: 9, blockDensity: 0.35, enemies: [{ type: 'slime', count: 3 }], reward: 100, xpReward: 50, unlockLevel: 1, icon: 'leaf', shardReward: 2 },
      { id: 'f2', name: 'Sentier', regionId: 'forest', stageNumber: 2, isBoss: false, width: 11, height: 9, blockDensity: 0.38, enemies: [{ type: 'slime', count: 5 }], reward: 150, xpReward: 75, unlockLevel: 1, icon: 'sprout', shardReward: 2 },
      { id: 'f3', name: 'Clairière', regionId: 'forest', stageNumber: 3, isBoss: false, width: 13, height: 9, blockDensity: 0.40, enemies: [{ type: 'slime', count: 4 }, { type: 'goblin', count: 2 }], reward: 200, xpReward: 100, unlockLevel: 2, icon: 'sun', shardReward: 2 },
      { id: 'f4', name: 'Grotte Sombre', regionId: 'forest', stageNumber: 4, isBoss: false, width: 13, height: 11, blockDensity: 0.42, enemies: [{ type: 'slime', count: 3 }, { type: 'goblin', count: 4 }], reward: 300, xpReward: 150, unlockLevel: 3, icon: 'cave', shardReward: 2 },
      { id: 'f5', name: 'Roi Slime', regionId: 'forest', stageNumber: 5, isBoss: true, width: 13, height: 11, blockDensity: 0.30, enemies: [{ type: 'slime', count: 2 }], boss: 'king-slime', reward: 800, xpReward: 400, unlockLevel: 3, icon: 'crown', shardReward: 10 },
    ],
  },
  {
    id: 'caves',
    name: 'Cavernes Maudites',
    icon: 'caves',
    description: 'Des galeries profondes habitées par les gobelins.',
    unlockLevel: 5,
    bgColor: 'hsl(30, 20%, 12%)',
    stages: [
      { id: 'c1', name: 'Entrée', regionId: 'caves', stageNumber: 1, isBoss: false, width: 13, height: 9, blockDensity: 0.42, enemies: [{ type: 'goblin', count: 5 }], reward: 250, xpReward: 125, unlockLevel: 5, icon: 'rock', shardReward: 3 },
      { id: 'c2', name: 'Mine', regionId: 'caves', stageNumber: 2, isBoss: false, width: 13, height: 11, blockDensity: 0.45, enemies: [{ type: 'goblin', count: 4 }, { type: 'skeleton', count: 2 }], reward: 350, xpReward: 175, unlockLevel: 6, icon: 'hammer', shardReward: 3 },
      { id: 'c3', name: 'Crypte', regionId: 'caves', stageNumber: 3, isBoss: false, width: 15, height: 11, blockDensity: 0.45, enemies: [{ type: 'skeleton', count: 5 }, { type: 'goblin', count: 3 }], reward: 500, xpReward: 250, unlockLevel: 7, icon: 'coffin', shardReward: 3 },
      { id: 'c4', name: 'Salle du Trône', regionId: 'caves', stageNumber: 4, isBoss: false, width: 15, height: 11, blockDensity: 0.48, enemies: [{ type: 'goblin', count: 6 }, { type: 'skeleton', count: 3 }], reward: 600, xpReward: 300, unlockLevel: 8, icon: 'throne', shardReward: 3 },
      { id: 'c5', name: 'Chef Gobelin', regionId: 'caves', stageNumber: 5, isBoss: true, width: 15, height: 11, blockDensity: 0.30, enemies: [{ type: 'goblin', count: 3 }], boss: 'goblin-chief', reward: 1500, xpReward: 750, unlockLevel: 9, icon: 'sword', shardReward: 15 },
    ],
  },
  {
    id: 'ruins',
    name: 'Ruines Anciennes',
    icon: 'ruins',
    description: 'Des ruines hantées par la Liche et ses morts-vivants.',
    unlockLevel: 12,
    bgColor: 'hsl(270, 20%, 12%)',
    stages: [
      { id: 'r1', name: 'Parvis', regionId: 'ruins', stageNumber: 1, isBoss: false, width: 15, height: 11, blockDensity: 0.45, enemies: [{ type: 'skeleton', count: 6 }], reward: 500, xpReward: 250, unlockLevel: 12, icon: 'grave', shardReward: 4 },
      { id: 'r2', name: 'Bibliothèque', regionId: 'ruins', stageNumber: 2, isBoss: false, width: 15, height: 11, blockDensity: 0.48, enemies: [{ type: 'skeleton', count: 5 }, { type: 'goblin', count: 3 }], reward: 700, xpReward: 350, unlockLevel: 13, icon: 'book', shardReward: 4 },
      { id: 'r3', name: 'Catacombes', regionId: 'ruins', stageNumber: 3, isBoss: false, width: 17, height: 11, blockDensity: 0.50, enemies: [{ type: 'skeleton', count: 8 }], reward: 900, xpReward: 450, unlockLevel: 15, icon: 'skull', shardReward: 4 },
      { id: 'r4', name: 'Sanctuaire', regionId: 'ruins', stageNumber: 4, isBoss: false, width: 17, height: 13, blockDensity: 0.50, enemies: [{ type: 'skeleton', count: 6 }, { type: 'orc', count: 2 }], reward: 1200, xpReward: 600, unlockLevel: 17, icon: 'candle', shardReward: 4 },
      { id: 'r5', name: 'Liche Noire', regionId: 'ruins', stageNumber: 5, isBoss: true, width: 17, height: 13, blockDensity: 0.28, enemies: [{ type: 'skeleton', count: 4 }], boss: 'lich', reward: 3000, xpReward: 1500, unlockLevel: 18, icon: 'reaper', shardReward: 20 },
    ],
  },
  {
    id: 'fortress',
    name: 'Forteresse Orc',
    icon: 'fortress',
    description: 'La forteresse des orcs, bâtie sur la roche volcanique.',
    unlockLevel: 22,
    bgColor: 'hsl(15, 25%, 12%)',
    stages: [
      { id: 'o1', name: 'Remparts', regionId: 'fortress', stageNumber: 1, isBoss: false, width: 17, height: 11, blockDensity: 0.50, enemies: [{ type: 'orc', count: 4 }, { type: 'goblin', count: 3 }], reward: 1000, xpReward: 500, unlockLevel: 22, icon: 'brick', shardReward: 5 },
      { id: 'o2', name: 'Caserne', regionId: 'fortress', stageNumber: 2, isBoss: false, width: 17, height: 13, blockDensity: 0.52, enemies: [{ type: 'orc', count: 6 }], reward: 1400, xpReward: 700, unlockLevel: 24, icon: 'helmet', shardReward: 5 },
      { id: 'o3', name: 'Armurerie', regionId: 'fortress', stageNumber: 3, isBoss: false, width: 19, height: 13, blockDensity: 0.52, enemies: [{ type: 'orc', count: 5 }, { type: 'skeleton', count: 4 }], reward: 1800, xpReward: 900, unlockLevel: 26, icon: 'blade', shardReward: 5 },
      { id: 'o4', name: 'Donjon', regionId: 'fortress', stageNumber: 4, isBoss: false, width: 19, height: 13, blockDensity: 0.55, enemies: [{ type: 'orc', count: 7 }, { type: 'demon', count: 1 }], reward: 2500, xpReward: 1250, unlockLevel: 28, icon: 'lock', shardReward: 5 },
      { id: 'o5', name: 'Seigneur Orc', regionId: 'fortress', stageNumber: 5, isBoss: true, width: 19, height: 13, blockDensity: 0.28, enemies: [{ type: 'orc', count: 3 }], boss: 'orc-warlord', reward: 6000, xpReward: 3000, unlockLevel: 30, icon: 'axe', shardReward: 25 },
    ],
  },
  {
    id: 'inferno',
    name: 'Enfer Ardent',
    icon: 'inferno',
    description: 'Le domaine du Seigneur Démon, au cœur du volcan.',
    unlockLevel: 35,
    bgColor: 'hsl(0, 30%, 12%)',
    stages: [
      { id: 'i1', name: 'Porte de Feu', regionId: 'inferno', stageNumber: 1, isBoss: false, width: 19, height: 13, blockDensity: 0.52, enemies: [{ type: 'demon', count: 4 }, { type: 'orc', count: 3 }], reward: 2000, xpReward: 1000, unlockLevel: 35, icon: 'door', shardReward: 6 },
      { id: 'i2', name: 'Lac de Lave', regionId: 'inferno', stageNumber: 2, isBoss: false, width: 19, height: 13, blockDensity: 0.55, enemies: [{ type: 'demon', count: 6 }], reward: 3000, xpReward: 1500, unlockLevel: 37, icon: 'waves', shardReward: 6 },
      { id: 'i3', name: 'Tour Noire', regionId: 'inferno', stageNumber: 3, isBoss: false, width: 21, height: 13, blockDensity: 0.55, enemies: [{ type: 'demon', count: 5 }, { type: 'skeleton', count: 5 }], reward: 4000, xpReward: 2000, unlockLevel: 40, icon: 'tower', shardReward: 6 },
      { id: 'i4', name: 'Chambre du Trône', regionId: 'inferno', stageNumber: 4, isBoss: false, width: 21, height: 15, blockDensity: 0.55, enemies: [{ type: 'demon', count: 8 }], reward: 5500, xpReward: 2750, unlockLevel: 43, icon: 'fire-crown', shardReward: 6 },
      { id: 'i5', name: 'Seigneur Démon', regionId: 'inferno', stageNumber: 5, isBoss: true, width: 21, height: 15, blockDensity: 0.25, enemies: [{ type: 'demon', count: 3 }], boss: 'demon-lord', reward: 15000, xpReward: 7500, unlockLevel: 45, icon: 'demon', shardReward: 30 },
    ],
  },
  {
    id: 'swamp',
    name: 'Marais Maudits',
    icon: 'swamp',
    description: 'Un marais empoisonné où les morts-vivants pullulent sous le règne de la Reine des Marais.',
    unlockLevel: 40,
    bgColor: 'hsl(100, 25%, 10%)',
    stages: [
      { id: 's1', name: 'Brumes Putrides', regionId: 'swamp', stageNumber: 1, isBoss: false, width: 21, height: 13, blockDensity: 0.52, enemies: [{ type: 'zombie', count: 5 }, { type: 'skeleton', count: 3 }], reward: 4500, xpReward: 2250, unlockLevel: 40, icon: 'fog', shardReward: 7 },
      { id: 's2', name: 'Marécage Infernal', regionId: 'swamp', stageNumber: 2, isBoss: false, width: 21, height: 15, blockDensity: 0.55, enemies: [{ type: 'zombie', count: 7 }], reward: 6000, xpReward: 3000, unlockLevel: 42, icon: 'droplet', shardReward: 7 },
      { id: 's3', name: 'Cimetière Englouti', regionId: 'swamp', stageNumber: 3, isBoss: false, width: 23, height: 15, blockDensity: 0.55, enemies: [{ type: 'zombie', count: 6 }, { type: 'skeleton', count: 5 }], reward: 8000, xpReward: 4000, unlockLevel: 44, icon: 'grave', shardReward: 7 },
      { id: 's4', name: 'Antre Empoisonnée', regionId: 'swamp', stageNumber: 4, isBoss: false, width: 23, height: 15, blockDensity: 0.57, enemies: [{ type: 'zombie', count: 8 }, { type: 'demon', count: 2 }], reward: 10000, xpReward: 5000, unlockLevel: 46, icon: 'skull', shardReward: 7 },
      { id: 's5', name: 'Reine des Marais', regionId: 'swamp', stageNumber: 5, isBoss: true, width: 23, height: 15, blockDensity: 0.25, enemies: [{ type: 'zombie', count: 4 }], boss: 'swamp-queen', reward: 25000, xpReward: 12500, unlockLevel: 47, icon: 'crown', shardReward: 35 },
    ],
  },
  {
    id: 'arcane',
    name: 'Citadelle des Arcanes',
    icon: 'arcane',
    description: 'Une citadelle volante corrompue par la magie noire, gardée par l\'Archimage Corrompu.',
    unlockLevel: 48,
    bgColor: 'hsl(270, 30%, 10%)',
    stages: [
      { id: 'a1', name: 'Enceinte Mystique', regionId: 'arcane', stageNumber: 1, isBoss: false, width: 23, height: 15, blockDensity: 0.55, enemies: [{ type: 'mage', count: 4 }, { type: 'skeleton', count: 4 }], reward: 12000, xpReward: 6000, unlockLevel: 48, icon: 'star', shardReward: 8 },
      { id: 'a2', name: 'Bibliothèque Interdite', regionId: 'arcane', stageNumber: 2, isBoss: false, width: 23, height: 15, blockDensity: 0.57, enemies: [{ type: 'mage', count: 6 }], reward: 16000, xpReward: 8000, unlockLevel: 50, icon: 'book', shardReward: 8 },
      { id: 'a3', name: 'Tour de Cristal', regionId: 'arcane', stageNumber: 3, isBoss: false, width: 25, height: 15, blockDensity: 0.57, enemies: [{ type: 'mage', count: 5 }, { type: 'zombie', count: 5 }], reward: 20000, xpReward: 10000, unlockLevel: 52, icon: 'gem', shardReward: 8 },
      { id: 'a4', name: 'Nexus Arcanique', regionId: 'arcane', stageNumber: 4, isBoss: false, width: 25, height: 17, blockDensity: 0.58, enemies: [{ type: 'mage', count: 8 }, { type: 'demon', count: 3 }], reward: 28000, xpReward: 14000, unlockLevel: 54, icon: 'zap', shardReward: 8 },
      { id: 'a5', name: 'Archimage Corrompu', regionId: 'arcane', stageNumber: 5, isBoss: true, width: 25, height: 17, blockDensity: 0.22, enemies: [{ type: 'mage', count: 4 }], boss: 'archmage', reward: 50000, xpReward: 25000, unlockLevel: 56, icon: 'wand', shardReward: 50 },
    ],
  },
];
